"""brushes: the cross-project painter library for paintlib atlases. See brushes/README.md for the rules.

A brush is a painter (context -> RGB or RGBA) registered with metadata: material, the fixture its swatch is
rendered on, whether it paints a tinted (TintMask) part, the styles it suits, where it came from, and a version.
A style is a JSON profile in brushes/styles/: its finish (toon or soft painted look), palette, ink settings, and a
painter for each role ("wood", "brass", "team cloth", "quilted cloth" ...), each pinned to a brush version.

    import brushes
    style = brushes.use_style("painted-toon")            # activates its palette and finish for every brush
    atlas.add(shaft, style.painter("wood", axis=1))      # role -> pinned brush, profile options + yours
    atlas.add(strap, style.painter("embroidered band", along_samples=along, half_samples=halves), tint=True)
    brushes.painter("metal.iron@1", base="Brass")        # a brush directly, by key

A project points at a style in features/art-direction.md ("Style profile: painted-toon") and adds its own colours
with use_style(name, palette=style_module.PALETTE). The catalog (brushes/CATALOG.md, catalog.json) and swatch
sheets (brushes/swatches/<style>.png) are regenerated by `node blend.js brushes`.
"""

import json
import os

from . import core
from .registry import REGISTRY, Brush, brush, get
from . import cloth, fibre, fire, foliage, food, fur, leather, metal, plant, roof, stone, terrain, water, wood  # noqa: F401  (importing registers their brushes)
from . import wrap  # noqa: F401  (painter wrappers: brushes.wrap.in_frame, baked_tint, sooted, glowing ...)

STYLE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "styles")


class Style:
    def __init__(self, name, data):
        self.name = name
        self.data = data
        self.ink = dict(data.get("ink") or {})

    @property
    def roles(self):
        return sorted(self.data.get("painters", {}))

    def entry(self, role):
        painters = self.data.get("painters", {})
        if role not in painters:
            raise KeyError(f"style {self.name} has no painter for role {role!r}; it has {self.roles}. Pick a brush from the catalog or write one, then add the role")
        return painters[role]

    def brush(self, role):
        return get(self.entry(role)["brush"])

    def painter(self, role, **options):
        entry = self.entry(role)
        merged = dict(entry.get("options", {}))
        merged.update(options)
        return get(entry["brush"]).bind(**merged)


def styles():
    return sorted(name[:-5] for name in os.listdir(STYLE_DIR) if name.endswith(".json"))


def load(name):
    path = os.path.join(STYLE_DIR, f"{name}.json")
    if not os.path.exists(path):
        raise KeyError(f"no style {name!r}; styles: {styles()}")
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def use_style(name, palette=None, finish=None):
    """Load a style and make it the active one (palette and finish every brush reads). A project's own palette
    entries (palette=) are added on top of the style's."""
    data = load(name)
    merged_palette = dict(data.get("palette", {}))
    merged_palette.update(palette or {})
    merged_finish = dict(data.get("finish", {}))
    merged_finish.update(finish or {})
    core.activate(merged_palette, merged_finish)
    return Style(name, data)


def painter(key, **options):
    return get(key).bind(**options)


def catalog():
    return [REGISTRY[key].meta() for key in sorted(REGISTRY)]
